#!/bin/bash
set -euo pipefail

usage() {
    cat <<'EOF'
Usage:
  checksums.sh [SOURCE_DIR] [OUTPUT_FILE]       Generate checksums
  checksums.sh --verify CHECKSUM_FILE [SOURCE_DIR]  Verify checksums
  checksums.sh --help                           Show this help

Generate mode (default):
  SOURCE_DIR   Directory to checksum (default: current directory)
  OUTPUT_FILE  Where to write checksums (default: ./checksums.sha256)

  Recursively hashes all files under SOURCE_DIR using SHA256.
  Paths are stored relative to SOURCE_DIR so the file is portable.

Verify mode:
  CHECKSUM_FILE  A checksum file previously generated by this script
  SOURCE_DIR     Directory containing the files (default: current directory)

  Checks each file against its stored hash and reports results.

Examples:
  checksums.sh ~/Photos                         # hash everything in ~/Photos
  checksums.sh ~/Photos ~/Photos/checksums.sha256
  checksums.sh --verify checksums.sha256         # verify from current dir
  checksums.sh --verify checksums.sha256 ~/Photos
EOF
}

generate() {
    local source_dir="$1"
    local output_file="$2"

    if [[ ! -d "$source_dir" ]]; then
        echo "ERROR: Directory not found: $source_dir"
        exit 1
    fi

    # Resolve to absolute path so the output file path comparison works
    source_dir="$(cd "$source_dir" && pwd)"

    # Resolve output file to absolute path for comparison
    # (handle both existing and not-yet-existing files)
    local output_abs
    output_abs="$(cd "$(dirname "$output_file")" 2>/dev/null && pwd)/$(basename "$output_file")" || output_abs="$output_file"

    echo "Generating SHA256 checksums for: $source_dir"

    local count=0
    # Find all files, sort for consistency, hash them with paths relative to source_dir
    # Exclude the output file itself if it's inside source_dir
    (cd "$source_dir" && find . -type f -print0 | sort -z | while IFS= read -r -d '' file; do
        # Strip leading ./
        local relpath="${file#./}"
        # Skip the output file if it lives inside the source directory
        if [[ "$source_dir/$relpath" == "$output_abs" ]]; then
            continue
        fi
        sha256sum "$relpath"
    done) > "$output_file"

    count=$(wc -l < "$output_file")
    echo "Wrote $count checksums to: $output_file"
}

verify() {
    local checksum_file="$1"
    local source_dir="$2"

    if [[ ! -f "$checksum_file" ]]; then
        echo "ERROR: Checksum file not found: $checksum_file"
        exit 1
    fi

    if [[ ! -d "$source_dir" ]]; then
        echo "ERROR: Directory not found: $source_dir"
        exit 1
    fi

    # Resolve checksum file to absolute path before cd
    checksum_file="$(cd "$(dirname "$checksum_file")" && pwd)/$(basename "$checksum_file")"

    echo "Verifying checksums against: $source_dir"

    local ok=0
    local failed=0
    local missing=0
    local total=0

    cd "$source_dir"

    while IFS= read -r line; do
        # Each line is: <hash>  <filename>  (two spaces between)
        local hash="${line%% *}"
        local file="${line#*  }"
        total=$((total + 1))

        if [[ ! -e "$file" ]]; then
            echo "MISSING: $file"
            missing=$((missing + 1))
        else
            local actual
            actual="$(sha256sum "$file")"
            actual="${actual%% *}"
            if [[ "$hash" == "$actual" ]]; then
                ok=$((ok + 1))
            else
                echo "FAILED: $file"
                failed=$((failed + 1))
            fi
        fi
    done < "$checksum_file"

    echo ""
    echo "Total: $total  OK: $ok  FAILED: $failed  MISSING: $missing"

    if [[ $failed -gt 0 || $missing -gt 0 ]]; then
        exit 1
    fi
}

# Parse arguments
if [[ $# -gt 0 && "$1" == "--help" ]]; then
    usage
    exit 0
fi

if [[ $# -gt 0 && "$1" == "--verify" ]]; then
    shift
    if [[ $# -lt 1 ]]; then
        echo "ERROR: --verify requires a checksum file"
        echo "Run checksums.sh --help for usage"
        exit 1
    fi
    checksum_file="$1"
    source_dir="${2:-.}"
    verify "$checksum_file" "$source_dir"
else
    source_dir="${1:-.}"
    output_file="${2:-./checksums.sha256}"
    generate "$source_dir" "$output_file"
fi
