;;; helm-z-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-z.el

(autoload 'helm-z "helm-z" "\
Show z directory list by helm." t)
(register-definition-prefixes "helm-z" '("helm-z-"))

;;; End of scraped data

(provide 'helm-z-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-z-autoloads.el ends here
